# Site settings
title: Twentyfour
description: "The 24 game solver by Daphne Soegijono."
baseurl: "/twentyfour"
url: "http://dsoegijono.github.io/"

# Build settings
markdown: kramdown
permalink: pretty
